### ISSUE TITLE
images/checkpoint: can't pull pod-checkpointer from a private proxy repo

### ISSUE THREAD

**Issue by stuart-warren** [kubernetes-incubator/bootkube#180]
I notice that the pod-checkpointer actually refers to itself in the pod that /checkpoint-install.sh creates.

We've been tinkering on a fork of bootkube with our own default network details/templates. 

Currently the bootkube api-server pod pulls the pod-checkpointer image from our proxy repo, but then the checkpoint-install.sh script installs a pod forcing a download of pod-checkpointer again from the internet.

Would we be ok using sed to insert the repo url into `checkpoint/checkpoint-pod.yaml` during `checkpoint/checkpoint-install.sh` rather than `checkpoint/build-image.sh`, obviously with a default of quay.io ?

**Comment by aaronlevy** [comment]
Hmmm. That is a good point.

I'm a bit hesitant to try and have this pull down arbitrary images at runtime based on sed. Maybe unfounded concern - but from an operational perspective this seems like it could become confusing pretty easily (albeit the default wouldn't change).

I don't immediately have a more preferable solution. Might need to think on this for a little bit.

**Comment by aaronlevy** [comment]
Been thinking about this a bit,

I'm not super happy with how we essentially are installing a somewhat "hidden" manifest - which requires re-building an image to change anything about it. If it's updating the binary, that's one thing,  but needing a rebuild just to change options in the manifest feels wrong.

One option might be to make use of the podTemplate api. Essentially a cold-storage for a pod from which we can essentially make cookie-cutter copies.

This might look like:

**checkpoint-pod-template.yaml**

```
apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-checkpointer
  namespace: kube-system
template:
  metadata:
    name: pod-checkpointer
    namespace: kube-system
    labels:
      k8s-app: pod-checkpointer
  spec:
    containers:
    - name: checkpoint
      image: quay.io/coreos/pod-checkpointer:foo
      command:
      - /checkpoint
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /etc/kubernetes
        name: etc-kubernetes
      - mountPath: /srv/kubernetes
        name: srv-kubernetes
    hostNetwork: true
    restartPolicy: Always
    volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: srv-kubernetes
      hostPath:
        path: /srv/kubernetes
```

Then we create that template entry:

```
kubectl create -f checkpoint-pod-template.yaml
```

Then our "checkpoint-installer" is changed to (in psuedo steps):

1. curl /api/v1/namespaces/kube-system/podtemlates/pod-checkpointer
2. create static pod from pod-checkpointer template

Any customizations that a user needs to make can then just be made to an actual api-object rather than relying on re-building an image just to change the manifest.
