### ISSUE TITLE
service IP to remote host-networking pod does not work in vagrant

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#194]
In the vagrant hack examples, you cannot reach a remote pod via service IP when that remote pod is using host-networking.

Repro

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    name: n1
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
```

```
kubectl create -f pod.yaml
kubectl expose pod n1 --port=80
kubectl get service n1
```

Then from a different machine than n1 is running on, try and curl the service IP from the host.
