### ISSUE TITLE
Add rolling update strategy to all daemonsets

### ISSUE THREAD

**Issue by diegs** [kubernetes-incubator/bootkube#547]
We should add the rolling update strategy to all our daemonsets.

```
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
