### ISSUE TITLE
http_proxy support

### ISSUE THREAD

**Issue by janwillies** [kubernetes-incubator/bootkube#556]
I'm trying to get bootkube working when there's only an http_proxy available to communicate with the internet. Since we are running on AWS, the apiserver and controller-manager need to talk to the AWS API.

After `bootkube render` I edited the following files and added 

- assets/bootstrap-manifests/bootstrap-apiserver.yaml 
- assets/bootstrap-manifests/bootstrap-controller-manager.yaml
- assets/manifests/kube-apiserver.yaml 
- assets/manifests/kube-controller-manager.yaml

```
    env:
    - name: http_proxy
      value: http://proxy.foo.bar:8080
    - name: https_proxy
      value: http://proxy.foo.bar:8080
    - name: no_proxy
      value: localhost,127.0.0.1,.compute.internal,169.254.169.254,10.3.0.1,10.3.0.15
```
Notice the apiserver and etcd internal addresses in `no_proxy`. This works fine and bootkube brings up all components but there are still some issues (I think)

Note:
At some point the variables are stripped from the pods and thus the new apiserver pod can't start successfully (times out when trying to reach the AWS API). I think it might be a timing issue, b/c when I change the aws health-check to a lower value (instances get healthier quickly) it works. Can't reproduce anymore, but it went something like this:
- bootstrap apiserver pod has the variables.
- first apiserver pod has the variables. Is killed at some point and a new apiserver is spawned
- second apiserver pod **doesn't** have the variables.
