### ISSUE TITLE
etcd-operator on aws s3 backups

### ISSUE THREAD

**Issue by sstarcher** [kubernetes-incubator/bootkube#581]
Setup:
* bootkube 0.4.4
* aws
* self hosted etcd

Change:
* configuring the etcd-operator to backup to an s3 bucket
```
  backup:
    backupIntervalInSecond: 300
    maxBackups: 5
    storageType: "S3"
    s3:
      s3Bucket: accessible-bucket
```

Reference: https://github.com/coreos/etcd-operator/issues/1196

In the above situation the etcd-operator attempts to create `/etc/etcd-operator` directory, but bootkube is setting the user to a non-root user who does not have access to create that directory.  

The result is the etcd-operator crashes the cluster.
