### ISSUE TITLE
KeepAlived VIP custom container during bootstrap process

### ISSUE THREAD

**Issue by andrewwebber** [kubernetes-incubator/bootkube#617]
After dropping a custom manifest into the bootstrap-manifests folder I was expecting the container to be launched even if the APIServer is not up. It appear to not honor my custom container. Is this because the bootstrap process can only handle pods?

This is important as I am trying to launch a KeepAlived container and have the APIServer ip address be a KeepAlived address. This would enable the kubeconfig to point to the KeepAlived VIP address allowing a master node to be shutdown. The bootstrapping process never completes because the keepalived container is never started.

This was tested following the CoreOS matchbox bootkube-install example.

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: keepalived
        image: brainloop/keepalived
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: KEEPALIVED_VIP
            value: "192.168.122.20"
          - name: ROUTER_ID
            value: "50"
```

**Comment by diegs** [comment]
Correct, items in `bootstrap-manifests` must be pods, as they are run statically by the kubelet (that is how bootstrapping works).

If you want a container to run during bootstrapping, it must be a Pod. Note that this Pod will also be removed when bootkube exits.

If you want a deployment to be permanently added to the cluster once the apiserver is up, you can add it to the `manifests` directory.

**Comment by andrewwebber** [comment]
@diegs thank you for the confirmation. I am now able to more forward successfully with the following amendment 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: bootstrap-keepalived
  namespace: kube-system
  labels:
    k8s-app: boot-keepalived
spec:
  hostNetwork: true
  containers:
  - name: keepalived
    image: brainloop/keepalived
    imagePullPolicy: Always
    securityContext:
      privileged: true
    env:
      - name: KEEPALIVED_VIP
        value: "10.10.4.20"
      - name: ROUTER_ID
        value: "50"

```
